version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - GO_ENV=test

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"